name: Lint

on: [pull_request, push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: mrdivyansh/eslint-action@1.0.6
        with:
          # GitHub repository token for publishing inline lint annotations. Should be secrets.GITHUB_TOKEN.
          repo-token: ${{secrets.GITHUB_TOKEN}}
